<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>asm</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>x86_64 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[;#].*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[\#%]\s*if\s+0\b</string>
			<key>end</key>
			<string>^\s*[\#%]\s*endif\b</string>
			<key>name</key>
			<string>comment.preprocessor</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(dword|qword|tword|db|dw|dd|dq|dt|do|dy|resb|resw|resd|resq|rest|reso|resy|incbin|equ|times)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(data|bss|text)$</string>
			<key>name</key>
			<string>string.section</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>["']</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.asm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>["']</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.asm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.asm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[#%]\s*(error|warning)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.error.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.preprocessor.diagnostic.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[#%]\s*(include|import)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.c</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*[%#]\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef|endif)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(aaa|aad|aam|aas|adc|add|and|arpl|bound|bsf|bsr|bswap|bt|btc|btr|bts|call|cbw|cdq|clc|cld|cli|clts|cmc|cmp|cmps|cmpxchg|cwd|cwde|daa|das|dec|div|enter|esc|hlt|idiv|imul|in|inc|ins|int|into|invd|invlpg|iret|iretd|ja|jae|jb|jbe|jc|jcxz|je|jecxz|jg|jge|jl|jle|jmp|jna|jnae|jnb|jnbe|jnc|jne|jng|jnge|jnl|jnle|jno|jnp|jns|jnz|jo|jp|jpe|jpo|js|jz|lahf|lar|lds|lea|leave|les|lfs|lgdt|lidt|lgs|lldt|lmsw|lock|lods|loop|loope|loopz|loopnz|loopne|lsl|lss|ltr|mov|movs|movsx|movzx|mul|near|neg|nop|not|or|out|outs|pop|popa|popad|popf|popfd|push|pusha|pushad|pushf|pushfd|rcl|rcr|rep|repe|repz|repne|repnz|ret|retf|rol|ror|sahf|sal|sar|sbb|scas|section|setae|setnb|setb|setnae|setbe|setna|sete|setz|setne|setnz|setl|setnge|setge|setng|setle|setng|setg|setnle|sets|setns|setc|setnc|seto|setno|setp|setpe|setnp|setpo|sgdt|sidt|shl|shld|shr|shrd|sldt|smsw|stc|std|sti|stos|str|sub|test|verr|verw|wait|fwait|wait|fwait|wbinvd|xchg|xlat|xlatb|xor)(l|w|b|q)?\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\.?\w+:\s*(?=$|;)</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.literal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9a-fA-F]+h?|0x[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\.?(globl|global)\b</string>
			<key>name</key>
			<string>entity.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b%?(ah|al|ax|bh|bl|bp|bpl|bx|ch|cl|cr0|cr1|cr10|cr11|cr12|cr13|cr14|cr15|cr2|cr3|cr4|cr5|cr6|cr7|cr8|cr9|cs|cw|cx|dh|di|dil|dl|dr0|dr1|dr10|dr11|dr12|dr13|dr14|dr15|dr2|dr3|dr4|dr5|dr6|dr7|dr8|dr9|ds|dx|eax|ebp|ebx|ecx|edi|edx|eflags|eip|es|esi|esp|flags|fp_cs|fp_dp|fp_ds|fp_ip|fp_opc|fs|gdtr|gs|idtr|ip|ldtr|mm0|mm1|mm2|mm3|mm4|mm5|mm6|mm7|msw|mxcsr|r10|r10d|r10l|r10w|r11|r11d|r11l|r11w|r12|r12d|r12l|r12w|r13|r13d|r13l|r13w|r14|r14d|r14l|r14w|r15|r15d|r15l|r15w|r8|r8d|r8l|r8w|r9|r9d|r9l|r9w|rax|rbp|rbx|rcx|rdi|rdx|rflags|rsi|rsp|si|sil|sp|spl|ss|st0|st1|st2|st3|st4|st5|st6|st7|sw|tr|tw|xmm0|xmm1|xmm10|xmm11|xmm12|xmm13|xmm14|xmm15|xmm2|xmm3|xmm4|xmm5|xmm6|xmm7|xmm8|xmm9|ymm0|ymm1|ymm10|ymm11|ymm12|ymm13|ymm14|ymm15|ymm2|ymm3|ymm4|ymm5|ymm6|ymm7|ymm8|ymm9|zmm0|zmm1|zmm10|zmm11|zmm12|zmm13|zmm14|zmm15|zmm16|zmm17|zmm18|zmm19|zmm2|zmm20|zmm21|zmm22|zmm23|zmm24|zmm25|zmm26|zmm27|zmm28|zmm29|zmm3|zmm30|zmm31|zmm4|zmm5|zmm6|zmm7|zmm8|zmm9)+\b</string>
			<key>name</key>
			<string>storage.register</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.x86_64</string>
	<key>uuid</key>
	<string>94DDB367-0875-4FF3-8047-D3FF2988B3C9</string>
</dict>
</plist>
