<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>1</string>
		<string>2</string>
		<string>3</string>
		<string>4</string>
		<string>5</string>
		<string>6</string>
		<string>7</string>
		<string>8</string>
		<string>9</string>
		<string>local</string>
	</array>
	<key>firstLineMatch</key>
	<string>\.[TH|Dd|Dt|Os]</string>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>mdoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([.'])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.roff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mdoc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^.*$</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>mdoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#special-characters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-decoration</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.roff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.roff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.roff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\G(ds)\s(\w+?)\s(.*?)$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.roff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.roff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\G(ad|am|ami|cc|de|\.|dei|de1|ds|el|EN|EQ|hy|ie|if|ig|ne|nh|rm|nr|nS|ns|ps|so|ta|tr|T&amp;|TE|TS)\s(.*?)$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.mdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.heading.mdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\G(SS|Ss|SH|Sh)\s(.*?)$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.mdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.mdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\G(TH|Nd|Dd|Dt|Os|%\w)\s(.*?)$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(Nm|Op|Bl|El|Fl|Ar|Cm|Aq|Ev|It|Xr|Rs|Re|An|Sy|Pp|PP|TP|sp|br|RS|ft|RE|Brq|Dq|Dl|Pa|Fn|Sq|Ns|St|Fx|Ao|Ac|Ic|Ta|Em|Xc|Dv|Pq|Qq|Tn)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.mdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mdoc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>-(tag|width|indent|offset|compact)</string>
					<key>name</key>
					<string>keyword.control.mdoc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\\]".*$</string>
					<key>name</key>
					<string>comment.line.roff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.roff</string>
				</dict>
			</array>
		</dict>
		<key>special-characters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\\(\S+|\\\[\w+?\])</string>
					<key>name</key>
					<string>support.constant.roff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\\*\S+|\\\*\[\w+?\])</string>
					<key>name</key>
					<string>support.constant.roff</string>
				</dict>
			</array>
		</dict>
		<key>text-decoration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\fC?[B|3]</string>
					<key>end</key>
					<string>\\f[1|R|P]</string>
					<key>name</key>
					<string>markup.bold.roff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>[\\]fC?[I|2]</string>
					<key>end</key>
					<string>[\\]f[1|R|P]</string>
					<key>name</key>
					<string>markup.italic.roff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>[\\]fC?BI</string>
					<key>end</key>
					<string>[\\]f[1|R|P]</string>
					<key>name</key>
					<string>markup.italic.bold.roff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\GIR?\s</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markup.italic.mdoc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\GBR?\s</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markup.bold.mdoc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G(BI|IB)R?\s</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markup.italic.bold.mdoc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.mdoc</string>
	<key>uuid</key>
	<string>2B5890DA-2ED3-49E7-8D1F-FFE341020AED</string>
</dict>
</plist>
